# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfc7238d1284499bf71ca032aebb744adc3b27a2c7325604194b33a1cdbed5e0b0c46d96d5d62200cf83c31fcbf8111ec02dad23d89eae11dcf6586d3f511980

test:
  secret_key_base: f365b2437c0d0643f577e9d15cc1e73ad64370b7011b599c13c78cc3f146931b0e580c27b70159239e40bc6149f4c3c34985a7d3218d26ff81af7852153cd992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
